name: lint-pylint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.8

      - name: Install dependencies
        run: poetry install

      - name: Lint with pylint module
        run: |
          pylint strava_api --ignore=_version.py -d C0330,W0622,R0913,R0903,W0511

      - name: Linth with pylint tests
        run: |
          pylint tests -d C0330,C0114,C0115,C0116,R0201,R0915,W0201,R0914,R0912,C0415,R0903,R0801,W0621,R1735
