name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.8

      - name: Install dependencies
        run: poetry install

      - name: create sample credentials
        run: |
          echo "email: email" >> ./strava-creds.yml
          echo "password: password" >> ./strava-creds.yml

      - name: Test with pytest
        run: |
          pytest -vv -l --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: codecov-umbrella
          fail_ci_if_error: true
